version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://pedrofragosoleandro:iL5NEWOr6Ggluayi@cluster0.8tfxs.mongodb.net/codesh-dictionary?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - VITE_PORT=5173

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
