# Dockerfile para a API
FROM node:20.16.0

# Define o diretório de trabalho
WORKDIR /usr/src/app

# Copia o arquivo de dependências para o container
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos
COPY . .

# Expõe a porta que a API vai rodar
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["npm", "run", "dev"]
